### PR TITLE
Refactor setup code

### PR DESCRIPTION
**Pull request by ManfredKarrer**

### CODE REVIEW

**Review by blabno — APPROVED** [review]
ACK. Tested against desktop and core on appropriate branches.

**Review by cbeams — APPROVED** [review]
utACK.

Thanks @blabno for your review.

@ManfredKarrer, it would be good to have even one sentence providing context about why these changes are being made / why now. I think I've inferred it from looking through this, and the other related PRs in other repositories, and I looked back through Slack because I thought I saw something from you and @blabno on the topic, but in general, this was a pretty inefficient review process for me, and I still don't feel that I have a strong grasp of the purpose of these changes. So I'm basically deferring to @blabno here, and doing a more cursory review on my side.

**Comment by ManfredKarrer** [comment]
@cbeams Yes, sorry I should have made a issue describing the motivation more clearly.

**Comment by cbeams** [comment]
Cool, and if you don’t want to create a separate issue, you can also just put details in the description of the first or and reference it from the other PRs (if any).

**Pull request merged**
