### PR TITLE
Support for blind voting

### PR DESCRIPTION
**Pull request by ManfredKarrer**

### CODE REVIEW

**Review by cbeams — APPROVED** [review]
utACK

The i18n stuff will obviously need to be shifted up to core after the merging of #8.

Without being super close to what you guys are doing here, it generally looks to me like an anti pattern to have to make protobuf changes at this level all the time.

I think we want to break up `pb.proto` for a number of reasons (one is that it's just far too big and causes everybody to have to do the painful IDEA custom properties workaround just to get code completion working), but more generally, it should be broken up so that protobuf stuff that needs to live only at the bisq-core or (possibly) even only at the bisq-desktop level can be made only at those levels without having to come touch stuff down here in common all the time.

Also, `Capabilities` is looking increasingly problematic, too. We shouldn't have something down here in bisq-common that's aware of all the higher-order functions / applications / capabilities in the system like seed nodes, compensation requests, etc. Again, I'm doing a cursory review here. Maybe there's some super important reason it needs to live here, but my default response would be to start looking for ways to redesign this problem out of existence.

**Review by sqrrm — APPROVED** [review]
utACK

**Comment by sqrrm** [comment]
@cbeams I agree that breaking up the protobuf file would be good. As you say, the parts could then be localized to the module they belong to, making it easier to understand what's being affected when working on them.

**Comment by ManfredKarrer** [comment]
Yes I agree as well with breaking up the PB stuff. It is just a bit tricky if you look closer to it, but that is easier explained in a phone call.
The Capabilities could be probably moved to 'p2p' but that would even be more alien there.
It is used to control network messages for different new features and not breaking backward compatibility (e.g. old clients don't disconnect a peer if they receive a unknown message type).

**Review by sqrrm — APPROVED** [review]
I don't see anything that would break normal operations. Prefer to have this in master than a long running branch so best to merge.

**Pull request merged**
